[application]

[web.app]
base_path = "app"

[[web.proxy]]
backend = "http://localhost:8080/api"

[[web.proxy]]
backend = "http://localhost:8080/login"

[[web.proxy]]
backend = "http://localhost:8080/logout"
